### ISSUE TITLE
ahk是个什么文件类型啊

### ISSUE THREAD

**Issue by GoddessLuBoYan** [ganlvtech/genshin-impact-ahk#1]
如题

**Comment by ganlvtech** [comment]
AutoHotKey 快捷键的脚本文件，主要用于按键映射、重复按键等，还有其他高级功能。可以用记事本打开查看和修改内容。

使用方法就是，从 AutoHotKey 官方网站下载并安装 [AutoHotKey 程序](https://www.autohotkey.com/download/ahk-install.exe) ，然后文件就可以被运行了。

**Comment by GoddessLuBoYan** [comment]
诶，那是不是对手柄类也有效啊
正愁部分游戏只能用键盘玩并不舒服

**Comment by ganlvtech** [comment]
@GoddessLuBoYan 没尝试过手柄，不太清楚
