### ISSUE TITLE
请问如果想修改按键的话需要用什么编辑器打开源文件

### ISSUE THREAD

**Issue by liuyx599** [ganlvtech/genshin-impact-ahk#3]

**Comment by ganlvtech** [comment]
右键打开方式，选择记事本。
或者在运行脚本的过程中，右下角图标右键点击，选择 Edit This Script。编辑之后保存，然后再选择 Reload This Script。
![image](https://user-images.githubusercontent.com/8651285/206818979-342aae40-2cd4-47d8-83cd-1579044f9826.png)
