### ISSUE TITLE
这个是报错吗？

### ISSUE THREAD

**Issue by llj437549** [ganlvtech/genshin-impact-ahk#5]
![IMG_20241117_175302](https://github.com/user-attachments/assets/8c7c7ec6-5d04-458f-be27-2278cb073296)
这是什么意思啊？

**Comment by ganlvtech** [comment]
AHK 更新 2.0 了，我这个代码是用 AHK 1.1 编写的，不兼容。让我想想办法

**Comment by ganlvtech** [comment]
我新提交了一个版本，改成 AutoHotKey v2 了，凑合用吧。我已经退坑了，电脑上已经没有这个游戏了，没法调试了。

**Comment by llj437549** [comment]
> 我新提交了一个版本，改成AutoHotKey v2了，凑合用吧。我已经退坑了，电脑上已经没有这个游戏了，无法调试了。

好的好的谢谢

**Comment by llj437549** [comment]
> 我新提交了一个版本，改成了AutoHotKey v2了，凑合用吧。我已经退坑了，电脑上已经没有这个游戏了，无法调试了。

谢谢大佬
